[window]

decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
option_as_alt = "Both"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 12.0

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[terminal]
shell = "/opt/homebrew/bin//tmux"
