[window]

decorations = "None"
opacity = 0.8
startup_mode = "Maximized"
option_as_alt = "Both"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 12.0

[font.bold]
family = "AdwaitaMono Nerd Font"
style = "Bold"

[font.italic]
family = "AdwaitaMono Nerd Font"
style = "Italic"

[font.normal]
family = "AdwaitaMono Nerd Font"
style = "Regular"

[terminal]
shell = {program = "/bin/bash", args  = ["-c", "/opt/homebrew/bin//tmux a || /opt/homebrew/bin//tmux"]}
