require "configs.telescope"
require("multicursor-nvim").setup()
require("Comment").setup()
require("todo-comments").setup()
require("log-highlight").setup {}
--
require "configs.barbar"
require "configs.kulala"
require "configs.tiny-code-action"
require "configs.oil"
require "configs.gomove"
require "configs.dapui"
require "configs.gitsigns"
require "configs.mini-diff"
require "configs.neotest"
require "configs.trouble"
require "configs.lualine"
require "configs.render-markdown"
require "lspconfig"
require "configs.lspconfig"
require "configs.diagnostic"
require "configs.trouble"
require "configs.text-case"
require "configs.illuminate"
require "configs.neotree"
require "configs.neogit-setup"
require "configs.dashboard"
require "configs.fidget"
require "configs.langmapper"
require "configs.siblingswap"
require "configs.nvimdap-virtual-text"
require "configs.noice"
require "configs.blink"
require "configs.minuet-ai"
require "configs.codecompanion"
require "configs.grapple"

require "configs.debuggers"
-- at the end, so all highlight rules can be applied
require "configs.material-theme"
require "highlight"
