[window]

decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

decorations_theme_variant = "Light" # "Dark"

[font]
size = 12.0

[font.bold]
family = "0xProtoNerdFont"
style = "Bold"

[font.italic]
family = "0xProtoNerdFont"
style = "Italic"

[font.normal]
family = "0xProtoNerdFont"
style = "Regular"

