unmap w W C S s u i
unmap <alt>, <alt>.

set update_title true
set colorscheme jungle
set show_selection_in_titlebar false
set preview_files false
set show_hidden false
set hidden_filter ^\.git$|^\.DS_Store$|^thumbs\.db$
set confirm_on_delete always

map l descend
map <CR> descend
map a console touch_or_mkdir%space
map A console create_directory%space
map r console rename %f
map d delete
map T trash_selection trash
map c copy
map x cut mode=add
map p paste_files
map y copy_path
map f fzf_files
map F fzf_rg
map oo open_in_new_tab
map L open_in_new_tab
map O open_in_file_manager
map e make_executable
map m edit_mode
map P toggle_preview
map <esc> chain change_mode normal; clear_all_selections

map zip console zip_create%space
map unzip extract_archive

map <A-t> tab_new
map <alt><C-t> tab_new
